Add workaround for mechanism_choices bug (#61)
NAS-136328 added special handling for return of available
authentication mechanisms so as to prevent authentication tokens
to be presented for sessions that have been authenticated using
a single-use-password. This was to prevent short-lived child
credentials from persisting across multiple sessions. Unfortunately
the fix introduced a regression for cases where the API endpoint
auth.mechanism_choices is called from an unauthenticated session.

Since the bug is present in multiple TrueNAS versions we can't
simply fix server-side, and so this commit adds a client-side
workaround where we treat the AttributeError:

"'NoneType' object has no attribute 'may_create_auth_token'"

as an authoritative indication that the remote server does
not accept SCRAM authentication.